### ISSUE TITLE
Working with 100's of quantities and adjustments

### ISSUE THREAD

**Issue by ddanninger** [Brille24/SyliusTierpricePlugin#56]
Hi there,

thanks for this great addition to sylius.

Did anyone expierence already some issues with 100's of quantities? 
We planned to use this plugin for like quantities of 250 - 1000 units.

The problem what i expierenced is that for all of those quantities it would run as many adjustments on the pricings and applieng coupons and stuff just makes it a huge mess and comes into database lock issues etc. For now i handled that with Memcache to not run in locking issues.

Did anybody solve that? Did you turn off automatic adjustments then? Or any suggestions how to handle 100's of quantities?

**Comment by mamazu** [comment]
Thanks for using our plugin.

Sadly we don't have a ready made solution for you. Currently Sylius creates for every product in the cart one object in the database. Messing with such a core behaviour is probably not a good idea. One simple to implement solution would be to create the article in tiers:

Like you have a product called nails. And you have a variant called 100 nails one called 10 Nails, one called 1 nail. If you do it like that you don't need tierpricing because you can customize that after generating the variants.
